workflows:
  ios-build:
    name: iOS Native Build
    labels:
      - ios
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "xcworkspace"   # или YourApp.xcworkspace, если используешь CocoaPods
        XCODE_SCHEME: "FinancialAdvisorApp"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install dependencies (CocoaPods)
        script: |
          gem install cocoapods
          pod install || true
      - name: Build iOS app
        script: |
          xcodebuild clean build \
          -project "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -destination 'generic/platform=iOS' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/**/Build/Products/**/*.app
      - build/**/Build/Products/**/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com